# Generated by Django 5.2.1 on 2025-05-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='fetched_question_text',
            new_name='problem_statement_html',
        ),
    ]
