# Generated by Django 5.2.1 on 2025-05-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_rename_fetched_question_text_question_problem_statement_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproblem',
            name='mark_for_revision',
            field=models.BooleanField(default=False),
        ),
    ]
